-- liquibase formatted sql

-- changeset scherbakov:1
CREATE TABLE IF NOT EXISTS notifiation_tasks
    (
        id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id               BIGINT NOT NULL,
        massage               TEXT NOT NULL,
        notifiation_date_time TIMESTAMP NOT NULL
);



